"""auth tables

Revision ID: d38e0e922ecd
Revises: 12bf7ba0df62
Create Date: 2026-01-20 16:42:41.857732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd38e0e922ecd'
down_revision: Union[str, Sequence[str], None] = '12bf7ba0df62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token_hash')
    )
    op.create_index('ix_auth_sessions_teacher_created', 'auth_sessions', ['teacher_id', 'created_at'], unique=False)
    op.create_table('otp_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('phone', 'email', name='otp_channel'), nullable=False),
    sa.Column('destination', sa.Text(), nullable=False),
    sa.Column('otp_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_otp_codes_destination_created', 'otp_codes', ['destination', 'created_at'], unique=False)
    op.create_index('ix_otp_codes_teacher_created', 'otp_codes', ['teacher_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session_feedback', 'suggestions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('session_feedback', 'observations',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_index('ix_otp_codes_teacher_created', table_name='otp_codes')
    op.drop_index('ix_otp_codes_destination_created', table_name='otp_codes')
    op.drop_table('otp_codes')
    op.drop_index('ix_auth_sessions_teacher_created', table_name='auth_sessions')
    op.drop_table('auth_sessions')
    # ### end Alembic commands ###
