"""add conversations and teaching insights

Revision ID: d872378fd96d
Revises: 48e201ae3b74
Create Date: 2026-01-22 00:16:17.271639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd872378fd96d'
down_revision: Union[str, Sequence[str], None] = '48e201ae3b74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teaching_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('generalized_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reframed_problem', sa.Text(), nullable=False),
    sa.Column('reframed_solution', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('raw_query', sa.Text(), nullable=False),
    sa.Column('resolved_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_response', sa.Text(), nullable=False),
    sa.Column('worked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_teacher_id'), 'conversations', ['teacher_id'], unique=False)
    op.create_table('teaching_insight_reactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('teaching_insight_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('liked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teaching_insight_id'], ['teaching_insights.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teaching_insight_id', 'teacher_id', name='uq_teacher_insight_reaction_once')
    )
    op.create_index(op.f('ix_teaching_insight_reactions_teacher_id'), 'teaching_insight_reactions', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_teaching_insight_reactions_teaching_insight_id'), 'teaching_insight_reactions', ['teaching_insight_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teaching_insight_reactions_teaching_insight_id'), table_name='teaching_insight_reactions')
    op.drop_index(op.f('ix_teaching_insight_reactions_teacher_id'), table_name='teaching_insight_reactions')
    op.drop_table('teaching_insight_reactions')
    op.drop_index(op.f('ix_conversations_teacher_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('teaching_insights')
    # ### end Alembic commands ###
